public class AppConstants {
    //Objects Constants
    //public static final String OBJ_ACCOUNT { get{ return 'Account'; }};
	public static final String OBJ_ACCOUNT = 'Account';
    public static final String OBJ_CASE = 'Case';
    public static final String OBJ_HH_MEMBER = 'HH_Member__c';
    public static final String OBJ_CA_STUDENT2 = 'CA_Student2__c';
    
    //RecordType Constants
    public static final String RT_CA = 'CA';
    public static final String RT_CA2 = 'CA2';
    public static final String RT_RRR = 'RRR';
    public static final String RT_CNREGISTRATION = 'CN_Registration';
    public static final String RT_SUREVEY_REQUEST = 'Survey_Request';
    public static final String RT_HH_MEMEBER_CA = 'CA2';
    public static final String RT_CA_STUDENT2_CA2 = 'CA2';
    public static final String RT_HOUSING_STIPEND = 'Housing_Stipend';
    public static final String RT_SCHOLARSHIP = 'Scholarship_Application';
    public static final String RT_CAMP_Case = 'CAMP_Case';
    public static final String RT_EA = 'Emergency_Assistance';
	public static final String RT_UA = 'Utility_Assistance';
    
    //Response Codes
    public static final String RESPONSE_CODE_OK = '200';
    public static final String RESPONSE_MESSAGE_OK = 'Success';
}