/*--------------------------------------------------------------------------------------------------------------
@Author: Alishba
@Date: June/02/2021
@Purpose: This class is used as controller for Community_SessionCheck aura component.
---------------------------------------------------------------------------------------------------------------*/


public without sharing class Community_SessionCheckController
{
    		PageReference pg = System.Page.SiteRegisterConfirm;
		//	system.debug('pg:' +pg);
  		 //   system.debug('geturl:' +pg.geturl());
}