/*--------------------------------------------------------------------------
@author: Shams
@date: 7/16/2021
@purpose: test class for GenRandomNumber
---------------------------------------------------------------------------*/
@istest
public class GenRandomNumberTest 
{
    @istest
    public static void runTest()
    {
        List<integer> intList=new List<integer>();
        intList.add(6);
        GenRandomNumber.GenRN(intList);
    }
}