/*--------------------------------------------------------------------------
@author: Alishba
@date: April/26/2021
@purpose: test class for MelissaDataController
---------------------------------------------------------------------------*/
@istest
public  class MelissaDataControllerTest 
{
      @istest
    public static void runTest()
    {
       MelissaDataController.SendRequest('1234 11th Ave, Phenix City, AL', 'United States'); 
    }

}